apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sdl-demo
  labels:
    app: eks-sdl-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-sdl-demo
  template:
    metadata:
      labels:
        app: eks-sdl-demo
    spec:
      containers:
      - name: eks-sdl-demo
        image: public.ecr.aws/h5r1n5l4/eks-razor-demo:v0.0.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
