apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

replicas:
- name: eks-sdl-demo
  count: 4

images:
- name: public.ecr.aws/h5r1n5l4/eks-razor-demo
  newTag: v1.0.0